# Generated by Django 4.2.7 on 2024-02-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=254, null=True)),
                ('vendor_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('vendor_gst', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_address', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
