# Generated by Django 4.2.7 on 2024-02-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_materialhistory_addrawmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrawmaterial',
            name='unit',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='unit',
            field=models.CharField(max_length=150),
        ),
    ]
